import 'package:flutter/cupertino.dart';
import 'package:sts/feature/students/widgets/student_card_widget.dart';

import '../../../utils/app_colors.dart';

class StudentsListWidget extends StatelessWidget {
  const StudentsListWidget({super.key});

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;

    return Column(
      children: [
        StudentCardWidget(
          initials: 'AC',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Aiden Clark',
          admissionNo: '0001',
          rollNo: '001',
          parentName: 'Sarah Clark',
          grade: 'A',
          gradeColor: const Color(0xFFFF6B35),
          gradeBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          percentage: '92%',
          percentageColor: AppColors.running,
          percentageBgColor: AppColors.running.withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'BM',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Bella Martinez',
          admissionNo: '0002',
          rollNo: '002',
          parentName: 'Luis Martinez',
          grade: 'B+',
          gradeColor: const Color(0xFFF59E0B),
          gradeBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
          percentage: '88%',
          percentageColor: const Color(0xFFF59E0B),
          percentageBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'CJ',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Carlos Johnson',
          admissionNo: '0003',
          rollNo: '003',
          parentName: 'Mike Johnson',
          grade: 'A+',
          gradeColor: const Color(0xFFFF6B35),
          gradeBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          percentage: '95%',
          percentageColor: AppColors.running,
          percentageBgColor: AppColors.running.withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'DL',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Diana Lee',
          admissionNo: '0004',
          rollNo: '004',
          parentName: 'Jenny Lee',
          grade: 'B',
          gradeColor: const Color(0xFFF59E0B),
          gradeBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
          percentage: '78%',
          percentageColor: const Color(0xFFF59E0B),
          percentageBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'EB',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Ethan Brown',
          admissionNo: '0005',
          rollNo: '005',
          parentName: 'Tom Brown',
          grade: 'A+',
          gradeColor: const Color(0xFFFF6B35),
          gradeBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          percentage: '98%',
          percentageColor: AppColors.running,
          percentageBgColor: AppColors.running.withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'FD',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Fiona Davis',
          admissionNo: '0006',
          rollNo: '006',
          parentName: 'Carol Davis',
          grade: 'A',
          gradeColor: const Color(0xFFFF6B35),
          gradeBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          percentage: '82%',
          percentageColor: const Color(0xFFF59E0B),
          percentageBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'GW',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'George Wilson',
          admissionNo: '0007',
          rollNo: '007',
          parentName: 'Paul Wilson',
          grade: 'B+',
          gradeColor: const Color(0xFFF59E0B),
          gradeBgColor: const Color(0xFFF59E0B).withOpacity(0.1),
          percentage: '90%',
          percentageColor: AppColors.running,
          percentageBgColor: AppColors.running.withOpacity(0.1),
        ),
        SizedBox(height: screenWidth * 0.03),
        StudentCardWidget(
          initials: 'HT',
          initialsColor: const Color(0xFFFF6B35),
          initialsBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          name: 'Hannah Thomas',
          admissionNo: '0008',
          rollNo: '008',
          parentName: 'Rachel Thomas',
          grade: 'A',
          gradeColor: const Color(0xFFFF6B35),
          gradeBgColor: const Color(0xFFFF6B35).withOpacity(0.1),
          percentage: '87%',
          percentageColor: AppColors.running,
          percentageBgColor: AppColors.running.withOpacity(0.1),
        ),
      ],
    );
  }
}